[2021-07-19 19:40:53,082] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: test.inaccurate 2021-07-19T17:38:36.773795+00:00 [queued]>
[2021-07-19 19:40:53,086] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: test.inaccurate 2021-07-19T17:38:36.773795+00:00 [queued]>
[2021-07-19 19:40:53,086] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-19 19:40:53,086] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-07-19 19:40:53,086] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-19 19:40:53,099] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): inaccurate> on 2021-07-19T17:38:36.773795+00:00
[2021-07-19 19:40:53,100] {standard_task_runner.py:52} INFO - Started process 13544 to run task
[2021-07-19 19:40:53,101] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'test', 'inaccurate', '2021-07-19T17:38:36.773795+00:00', '--job-id', '15', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/example.py', '--cfg-path', '/tmp/tmpz49rw9an', '--error-file', '/tmp/tmpi2526qtb']
[2021-07-19 19:40:53,101] {standard_task_runner.py:77} INFO - Job 15: Subtask inaccurate
[2021-07-19 19:40:53,120] {logging_mixin.py:104} INFO - Running <TaskInstance: test.inaccurate 2021-07-19T17:38:36.773795+00:00 [running]> on host DESKTOP-4B4VMOV.localdomain
[2021-07-19 19:40:53,150] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=test
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T17:38:36.773795+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-19T17:38:36.773795+00:00
[2021-07-19 19:40:53,150] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-07-19 19:40:53,150] {subprocess.py:63} INFO - Running command: ['bash', '-c', " echo 'inaccurate'"]
[2021-07-19 19:40:53,152] {subprocess.py:74} INFO - Output:
[2021-07-19 19:40:53,153] {subprocess.py:78} INFO - inaccurate
[2021-07-19 19:40:53,153] {subprocess.py:82} INFO - Command exited with return code 0
[2021-07-19 19:40:53,168] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=test, task_id=inaccurate, execution_date=20210719T173836, start_date=20210719T174053, end_date=20210719T174053
[2021-07-19 19:40:53,184] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-19 19:40:53,192] {local_task_job.py:149} INFO - Task exited with return code 0
